### ISSUE TITLE
Also Incosolata error in cordova crosswalk 

### ISSUE THREAD

**Issue by carricha** [safetychanger/font-roboto#1]
Hi,

Already thx for this contrib.

I suppose this is the way to go when building for cordova crosswalk.

I suppose I have to add this to bower.json for roboto font but I also get an loading error for Incolsolata.

I based my app on Polymer Starter Kit 1.0.2

What should I do for Inconlsolata ?

Rgds

**Comment by rubenstolk** [comment]
I guess this is out dated now
